// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v2

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for ConditionStatus.
const (
	ConditionStatusFalse   ConditionStatus = "False"
	ConditionStatusTrue    ConditionStatus = "True"
	ConditionStatusUnknown ConditionStatus = "Unknown"
)

// Defines values for HealthState.
const (
	HealthStateCritical HealthState = "critical"
	HealthStateHealthy  HealthState = "healthy"
	HealthStateInactive HealthState = "inactive"
	HealthStateUnknown  HealthState = "unknown"
	HealthStateWarning  HealthState = "warning"
)

// Defines values for PodViewExperience.
const (
	Classic PodViewExperience = "classic"
	Next    PodViewExperience = "next"
)

// Defines values for PodViewMode.
const (
	Default  PodViewMode = "default"
	Disabled PodViewMode = "disabled"
	OptIn    PodViewMode = "optIn"
	Required PodViewMode = "required"
)

// Defines values for TargetKind.
const (
	TargetKindMonoVertex     TargetKind = "MonoVertex"
	TargetKindPipelineVertex TargetKind = "PipelineVertex"
)

// Defines values for VertexType.
const (
	VertexTypeMapUDF     VertexType = "MapUDF"
	VertexTypeMonoVertex VertexType = "MonoVertex"
	VertexTypeReduceUDF  VertexType = "ReduceUDF"
	VertexTypeSink       VertexType = "Sink"
	VertexTypeSource     VertexType = "Source"
)

// ApiLimits defines model for ApiLimits.
type ApiLimits struct {
	DefaultPageSize     int `json:"defaultPageSize"`
	MaximumLogLines     int `json:"maximumLogLines"`
	MaximumMetricPoints int `json:"maximumMetricPoints"`
	MaximumPageSize     int `json:"maximumPageSize"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	ApiVersion string            `json:"apiVersion"`
	Limits     ApiLimits         `json:"limits"`
	Operations []string          `json:"operations"`
	PodView    PodViewCapability `json:"podView"`
}

// Condition defines model for Condition.
type Condition struct {
	LastTransitionTime time.Time       `json:"lastTransitionTime"`
	Message            *string         `json:"message,omitempty"`
	ObservedGeneration int64           `json:"observedGeneration"`
	Reason             string          `json:"reason"`
	Status             ConditionStatus `json:"status"`
	Type               string          `json:"type"`
}

// ConditionStatus defines model for Condition.Status.
type ConditionStatus string

// Health defines model for Health.
type Health struct {
	Message *string     `json:"message,omitempty"`
	Reason  *string     `json:"reason,omitempty"`
	State   HealthState `json:"state"`
}

// HealthState defines model for HealthState.
type HealthState string

// PodViewCapability defines model for PodViewCapability.
type PodViewCapability struct {
	AllowClassicFallback bool              `json:"allowClassicFallback"`
	DefaultExperience    PodViewExperience `json:"defaultExperience"`
	Eligible             bool              `json:"eligible"`
	Mode                 PodViewMode       `json:"mode"`
}

// PodViewExperience defines model for PodViewExperience.
type PodViewExperience string

// PodViewMode defines model for PodViewMode.
type PodViewMode string

// Problem defines model for Problem.
type Problem struct {
	Code       string       `json:"code"`
	Detail     string       `json:"detail"`
	Instance   string       `json:"instance"`
	Retryable  *bool        `json:"retryable,omitempty"`
	Status     int          `json:"status"`
	Title      string       `json:"title"`
	TraceId    *string      `json:"traceId,omitempty"`
	Type       string       `json:"type"`
	Violations *[]Violation `json:"violations,omitempty"`
}

// ReplicaStatus defines model for ReplicaStatus.
type ReplicaStatus struct {
	Current      int64 `json:"current"`
	Desired      int64 `json:"desired"`
	Ready        int64 `json:"ready"`
	Updated      int64 `json:"updated"`
	UpdatedReady int64 `json:"updatedReady"`
}

// TargetKind defines model for TargetKind.
type TargetKind string

// TargetRef defines model for TargetRef.
type TargetRef struct {
	Kind      TargetKind `json:"kind"`
	Name      string     `json:"name"`
	Namespace string     `json:"namespace"`
	Pipeline  *string    `json:"pipeline,omitempty"`
	Uid       string     `json:"uid"`
}

// VertexStatus defines model for VertexStatus.
type VertexStatus struct {
	Conditions         []Condition   `json:"conditions"`
	DesiredPhase       string        `json:"desiredPhase"`
	Generation         int64         `json:"generation"`
	Message            *string       `json:"message,omitempty"`
	ObservedAt         time.Time     `json:"observedAt"`
	ObservedGeneration int64         `json:"observedGeneration"`
	Phase              string        `json:"phase"`
	Reason             *string       `json:"reason,omitempty"`
	Ref                TargetRef     `json:"ref"`
	Replicas           ReplicaStatus `json:"replicas"`
	TruncatedFields    *[]string     `json:"truncatedFields,omitempty"`
}

// VertexSummary defines model for VertexSummary.
type VertexSummary struct {
	Capabilities       []string   `json:"capabilities"`
	CreatedAt          time.Time  `json:"createdAt"`
	DesiredPhase       string     `json:"desiredPhase"`
	Generation         int64      `json:"generation"`
	Health             Health     `json:"health"`
	LastScaledAt       *time.Time `json:"lastScaledAt,omitempty"`
	ObservedAt         time.Time  `json:"observedAt"`
	ObservedGeneration int64      `json:"observedGeneration"`
	Phase              string     `json:"phase"`
	Ref                TargetRef  `json:"ref"`
	TruncatedFields    *[]string  `json:"truncatedFields,omitempty"`
	VertexType         VertexType `json:"vertexType"`
}

// VertexType defines model for VertexType.
type VertexType string

// Violation defines model for Violation.
type Violation struct {
	AllowedValues *[]string `json:"allowedValues,omitempty"`
	Field         string    `json:"field"`
	Message       string    `json:"message"`
	Reason        string    `json:"reason"`
}

// IfNoneMatch defines model for IfNoneMatch.
type IfNoneMatch = string

// MonoVertex defines model for MonoVertex.
type MonoVertex = string

// Namespace defines model for Namespace.
type Namespace = string

// Pipeline defines model for Pipeline.
type Pipeline = string

// Vertex defines model for Vertex.
type Vertex = string

// Forbidden defines model for Forbidden.
type Forbidden = Problem

// InternalServerError defines model for InternalServerError.
type InternalServerError = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = Problem

// GetMonoVertexStatusParams defines parameters for GetMonoVertexStatus.
type GetMonoVertexStatusParams struct {
	// IfNoneMatch ETag from an earlier response
	IfNoneMatch *IfNoneMatch `json:"If-None-Match,omitempty"`
}

// GetMonoVertexSummaryParams defines parameters for GetMonoVertexSummary.
type GetMonoVertexSummaryParams struct {
	// IfNoneMatch ETag from an earlier response
	IfNoneMatch *IfNoneMatch `json:"If-None-Match,omitempty"`
}

// GetPipelineVertexStatusParams defines parameters for GetPipelineVertexStatus.
type GetPipelineVertexStatusParams struct {
	// IfNoneMatch ETag from an earlier response
	IfNoneMatch *IfNoneMatch `json:"If-None-Match,omitempty"`
}

// GetPipelineVertexSummaryParams defines parameters for GetPipelineVertexSummary.
type GetPipelineVertexSummaryParams struct {
	// IfNoneMatch ETag from an earlier response
	IfNoneMatch *IfNoneMatch `json:"If-None-Match,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCapabilities request
	GetCapabilities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMonoVertexStatus request
	GetMonoVertexStatus(ctx context.Context, namespace Namespace, monoVertex MonoVertex, params *GetMonoVertexStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMonoVertexSummary request
	GetMonoVertexSummary(ctx context.Context, namespace Namespace, monoVertex MonoVertex, params *GetMonoVertexSummaryParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPipelineVertexStatus request
	GetPipelineVertexStatus(ctx context.Context, namespace Namespace, pipeline Pipeline, vertex Vertex, params *GetPipelineVertexStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPipelineVertexSummary request
	GetPipelineVertexSummary(ctx context.Context, namespace Namespace, pipeline Pipeline, vertex Vertex, params *GetPipelineVertexSummaryParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCapabilities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCapabilitiesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMonoVertexStatus(ctx context.Context, namespace Namespace, monoVertex MonoVertex, params *GetMonoVertexStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMonoVertexStatusRequest(c.Server, namespace, monoVertex, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMonoVertexSummary(ctx context.Context, namespace Namespace, monoVertex MonoVertex, params *GetMonoVertexSummaryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMonoVertexSummaryRequest(c.Server, namespace, monoVertex, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPipelineVertexStatus(ctx context.Context, namespace Namespace, pipeline Pipeline, vertex Vertex, params *GetPipelineVertexStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPipelineVertexStatusRequest(c.Server, namespace, pipeline, vertex, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPipelineVertexSummary(ctx context.Context, namespace Namespace, pipeline Pipeline, vertex Vertex, params *GetPipelineVertexSummaryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPipelineVertexSummaryRequest(c.Server, namespace, pipeline, vertex, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCapabilitiesRequest generates requests for GetCapabilities
func NewGetCapabilitiesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/capabilities")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMonoVertexStatusRequest generates requests for GetMonoVertexStatus
func NewGetMonoVertexStatusRequest(server string, namespace Namespace, monoVertex MonoVertex, params *GetMonoVertexStatusParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "namespace", runtime.ParamLocationPath, namespace)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "monoVertex", runtime.ParamLocationPath, monoVertex)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/namespaces/%s/mono-vertices/%s/status", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IfNoneMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "If-None-Match", runtime.ParamLocationHeader, *params.IfNoneMatch)
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-None-Match", headerParam0)
		}

	}

	return req, nil
}

// NewGetMonoVertexSummaryRequest generates requests for GetMonoVertexSummary
func NewGetMonoVertexSummaryRequest(server string, namespace Namespace, monoVertex MonoVertex, params *GetMonoVertexSummaryParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "namespace", runtime.ParamLocationPath, namespace)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "monoVertex", runtime.ParamLocationPath, monoVertex)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/namespaces/%s/mono-vertices/%s/summary", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IfNoneMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "If-None-Match", runtime.ParamLocationHeader, *params.IfNoneMatch)
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-None-Match", headerParam0)
		}

	}

	return req, nil
}

// NewGetPipelineVertexStatusRequest generates requests for GetPipelineVertexStatus
func NewGetPipelineVertexStatusRequest(server string, namespace Namespace, pipeline Pipeline, vertex Vertex, params *GetPipelineVertexStatusParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "namespace", runtime.ParamLocationPath, namespace)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "pipeline", runtime.ParamLocationPath, pipeline)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "vertex", runtime.ParamLocationPath, vertex)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/namespaces/%s/pipelines/%s/vertices/%s/status", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IfNoneMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "If-None-Match", runtime.ParamLocationHeader, *params.IfNoneMatch)
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-None-Match", headerParam0)
		}

	}

	return req, nil
}

// NewGetPipelineVertexSummaryRequest generates requests for GetPipelineVertexSummary
func NewGetPipelineVertexSummaryRequest(server string, namespace Namespace, pipeline Pipeline, vertex Vertex, params *GetPipelineVertexSummaryParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "namespace", runtime.ParamLocationPath, namespace)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "pipeline", runtime.ParamLocationPath, pipeline)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "vertex", runtime.ParamLocationPath, vertex)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/namespaces/%s/pipelines/%s/vertices/%s/summary", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IfNoneMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "If-None-Match", runtime.ParamLocationHeader, *params.IfNoneMatch)
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-None-Match", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCapabilitiesWithResponse request
	GetCapabilitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCapabilitiesResponse, error)

	// GetMonoVertexStatusWithResponse request
	GetMonoVertexStatusWithResponse(ctx context.Context, namespace Namespace, monoVertex MonoVertex, params *GetMonoVertexStatusParams, reqEditors ...RequestEditorFn) (*GetMonoVertexStatusResponse, error)

	// GetMonoVertexSummaryWithResponse request
	GetMonoVertexSummaryWithResponse(ctx context.Context, namespace Namespace, monoVertex MonoVertex, params *GetMonoVertexSummaryParams, reqEditors ...RequestEditorFn) (*GetMonoVertexSummaryResponse, error)

	// GetPipelineVertexStatusWithResponse request
	GetPipelineVertexStatusWithResponse(ctx context.Context, namespace Namespace, pipeline Pipeline, vertex Vertex, params *GetPipelineVertexStatusParams, reqEditors ...RequestEditorFn) (*GetPipelineVertexStatusResponse, error)

	// GetPipelineVertexSummaryWithResponse request
	GetPipelineVertexSummaryWithResponse(ctx context.Context, namespace Namespace, pipeline Pipeline, vertex Vertex, params *GetPipelineVertexSummaryParams, reqEditors ...RequestEditorFn) (*GetPipelineVertexSummaryResponse, error)
}

type GetCapabilitiesResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *Capabilities
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetCapabilitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCapabilitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMonoVertexStatusResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *VertexStatus
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON422 *ValidationFailed
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetMonoVertexStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMonoVertexStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMonoVertexSummaryResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *VertexSummary
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON422 *ValidationFailed
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetMonoVertexSummaryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMonoVertexSummaryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPipelineVertexStatusResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *VertexStatus
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON422 *ValidationFailed
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetPipelineVertexStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPipelineVertexStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPipelineVertexSummaryResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *VertexSummary
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON422 *ValidationFailed
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetPipelineVertexSummaryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPipelineVertexSummaryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCapabilitiesWithResponse request returning *GetCapabilitiesResponse
func (c *ClientWithResponses) GetCapabilitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCapabilitiesResponse, error) {
	rsp, err := c.GetCapabilities(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCapabilitiesResponse(rsp)
}

// GetMonoVertexStatusWithResponse request returning *GetMonoVertexStatusResponse
func (c *ClientWithResponses) GetMonoVertexStatusWithResponse(ctx context.Context, namespace Namespace, monoVertex MonoVertex, params *GetMonoVertexStatusParams, reqEditors ...RequestEditorFn) (*GetMonoVertexStatusResponse, error) {
	rsp, err := c.GetMonoVertexStatus(ctx, namespace, monoVertex, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMonoVertexStatusResponse(rsp)
}

// GetMonoVertexSummaryWithResponse request returning *GetMonoVertexSummaryResponse
func (c *ClientWithResponses) GetMonoVertexSummaryWithResponse(ctx context.Context, namespace Namespace, monoVertex MonoVertex, params *GetMonoVertexSummaryParams, reqEditors ...RequestEditorFn) (*GetMonoVertexSummaryResponse, error) {
	rsp, err := c.GetMonoVertexSummary(ctx, namespace, monoVertex, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMonoVertexSummaryResponse(rsp)
}

// GetPipelineVertexStatusWithResponse request returning *GetPipelineVertexStatusResponse
func (c *ClientWithResponses) GetPipelineVertexStatusWithResponse(ctx context.Context, namespace Namespace, pipeline Pipeline, vertex Vertex, params *GetPipelineVertexStatusParams, reqEditors ...RequestEditorFn) (*GetPipelineVertexStatusResponse, error) {
	rsp, err := c.GetPipelineVertexStatus(ctx, namespace, pipeline, vertex, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPipelineVertexStatusResponse(rsp)
}

// GetPipelineVertexSummaryWithResponse request returning *GetPipelineVertexSummaryResponse
func (c *ClientWithResponses) GetPipelineVertexSummaryWithResponse(ctx context.Context, namespace Namespace, pipeline Pipeline, vertex Vertex, params *GetPipelineVertexSummaryParams, reqEditors ...RequestEditorFn) (*GetPipelineVertexSummaryResponse, error) {
	rsp, err := c.GetPipelineVertexSummary(ctx, namespace, pipeline, vertex, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPipelineVertexSummaryResponse(rsp)
}

// ParseGetCapabilitiesResponse parses an HTTP response from a GetCapabilitiesWithResponse call
func ParseGetCapabilitiesResponse(rsp *http.Response) (*GetCapabilitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCapabilitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Capabilities
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetMonoVertexStatusResponse parses an HTTP response from a GetMonoVertexStatusWithResponse call
func ParseGetMonoVertexStatusResponse(rsp *http.Response) (*GetMonoVertexStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMonoVertexStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VertexStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ValidationFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetMonoVertexSummaryResponse parses an HTTP response from a GetMonoVertexSummaryWithResponse call
func ParseGetMonoVertexSummaryResponse(rsp *http.Response) (*GetMonoVertexSummaryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMonoVertexSummaryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VertexSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ValidationFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetPipelineVertexStatusResponse parses an HTTP response from a GetPipelineVertexStatusWithResponse call
func ParseGetPipelineVertexStatusResponse(rsp *http.Response) (*GetPipelineVertexStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPipelineVertexStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VertexStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ValidationFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetPipelineVertexSummaryResponse parses an HTTP response from a GetPipelineVertexSummaryWithResponse call
func ParseGetPipelineVertexSummaryResponse(rsp *http.Response) (*GetPipelineVertexSummaryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPipelineVertexSummaryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VertexSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ValidationFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}
