/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/capabilities": {
    /** Get capabilities available to the current caller */
    get: operations["getCapabilities"];
  };
  "/namespaces/{namespace}/pipelines/{pipeline}/vertices/{vertex}/summary": {
    /** Get a compact pipeline vertex summary */
    get: operations["getPipelineVertexSummary"];
  };
  "/namespaces/{namespace}/pipelines/{pipeline}/vertices/{vertex}/status": {
    /** Get pipeline vertex controller status */
    get: operations["getPipelineVertexStatus"];
  };
  "/namespaces/{namespace}/mono-vertices/{monoVertex}/summary": {
    /** Get a compact MonoVertex summary */
    get: operations["getMonoVertexSummary"];
  };
  "/namespaces/{namespace}/mono-vertices/{monoVertex}/status": {
    /** Get MonoVertex controller status */
    get: operations["getMonoVertexStatus"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Capabilities: {
      /** @example v2 */
      apiVersion: string;
      podView: components["schemas"]["PodViewCapability"];
      /**
       * @example [
       *   "getPipelineVertexSummary",
       *   "getPipelineVertexStatus",
       *   "getMonoVertexSummary",
       *   "getMonoVertexStatus"
       * ]
       */
      operations: string[];
      limits: components["schemas"]["ApiLimits"];
    };
    PodViewCapability: {
      mode: components["schemas"]["PodViewMode"];
      eligible: boolean;
      defaultExperience: components["schemas"]["PodViewExperience"];
      allowClassicFallback: boolean;
    };
    /** @enum {string} */
    PodViewMode: "disabled" | "optIn" | "default" | "required";
    /** @enum {string} */
    PodViewExperience: "classic" | "next";
    ApiLimits: {
      /** @example 50 */
      defaultPageSize: number;
      /** @example 200 */
      maximumPageSize: number;
      /** @example 1000 */
      maximumLogLines: number;
      /** @example 2000 */
      maximumMetricPoints: number;
    };
    TargetRef: {
      kind: components["schemas"]["TargetKind"];
      namespace: string;
      pipeline?: string;
      name: string;
      uid: string;
    };
    /** @enum {string} */
    TargetKind: "PipelineVertex" | "MonoVertex";
    /** @enum {string} */
    VertexType: "Source" | "Sink" | "MapUDF" | "ReduceUDF" | "MonoVertex";
    Health: {
      state: components["schemas"]["HealthState"];
      reason?: string;
      message?: string;
    };
    /** @enum {string} */
    HealthState: "healthy" | "warning" | "critical" | "inactive" | "unknown";
    VertexSummary: {
      ref: components["schemas"]["TargetRef"];
      vertexType: components["schemas"]["VertexType"];
      phase: string;
      desiredPhase: string;
      health: components["schemas"]["Health"];
      /** Format: int64 */
      generation: number;
      /** Format: int64 */
      observedGeneration: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      observedAt: string;
      /** Format: date-time */
      lastScaledAt?: string;
      capabilities: string[];
      truncatedFields?: string[];
    };
    VertexStatus: {
      ref: components["schemas"]["TargetRef"];
      phase: string;
      desiredPhase: string;
      reason?: string;
      message?: string;
      replicas: components["schemas"]["ReplicaStatus"];
      conditions: components["schemas"]["Condition"][];
      /** Format: int64 */
      generation: number;
      /** Format: int64 */
      observedGeneration: number;
      /** Format: date-time */
      observedAt: string;
      truncatedFields?: string[];
    };
    ReplicaStatus: {
      /** Format: int64 */
      current: number;
      /** Format: int64 */
      desired: number;
      /** Format: int64 */
      ready: number;
      /** Format: int64 */
      updated: number;
      /** Format: int64 */
      updatedReady: number;
    };
    Condition: {
      type: string;
      /** @enum {string} */
      status: "True" | "False" | "Unknown";
      reason: string;
      message?: string;
      /** Format: int64 */
      observedGeneration: number;
      /** Format: date-time */
      lastTransitionTime: string;
    };
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      code: string;
      detail: string;
      /** Format: uri-reference */
      instance: string;
      traceId?: string;
      retryable?: boolean;
      violations?: components["schemas"]["Violation"][];
    };
    Violation: {
      field: string;
      reason: string;
      message: string;
      allowedValues?: string[];
    };
  };
  responses: {
    /** @description The target has not changed */
    NotModified: {
      headers: {
        ETag: components["headers"]["ETag"];
      };
      content: never;
    };
    /** @description Authentication is required or invalid */
    Unauthorized: {
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The caller cannot access this target */
    Forbidden: {
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The requested target does not exist */
    NotFound: {
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description One or more request fields are invalid */
    ValidationFailed: {
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The request could not be completed */
    InternalServerError: {
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    /** @description Kubernetes namespace containing the target */
    Namespace: string;
    /** @description Pipeline name */
    Pipeline: string;
    /** @description Vertex name within the pipeline */
    Vertex: string;
    /** @description MonoVertex name */
    MonoVertex: string;
    /** @description ETag from an earlier response */
    IfNoneMatch?: string;
  };
  requestBodies: never;
  headers: {
    /** @description Entity tag derived from the Kubernetes resource version */
    ETag: string;
  };
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get capabilities available to the current caller */
  getCapabilities: {
    responses: {
      /** @description Effective API and Pod View capabilities */
      200: {
        content: {
          "application/json": components["schemas"]["Capabilities"];
        };
      };
      401: components["responses"]["Unauthorized"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** Get a compact pipeline vertex summary */
  getPipelineVertexSummary: {
    parameters: {
      header?: {
        "If-None-Match"?: components["parameters"]["IfNoneMatch"];
      };
      path: {
        namespace: components["parameters"]["Namespace"];
        pipeline: components["parameters"]["Pipeline"];
        vertex: components["parameters"]["Vertex"];
      };
    };
    responses: {
      /** @description Pipeline vertex summary */
      200: {
        headers: {
          ETag: components["headers"]["ETag"];
        };
        content: {
          "application/json": components["schemas"]["VertexSummary"];
        };
      };
      304: components["responses"]["NotModified"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["ValidationFailed"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** Get pipeline vertex controller status */
  getPipelineVertexStatus: {
    parameters: {
      header?: {
        "If-None-Match"?: components["parameters"]["IfNoneMatch"];
      };
      path: {
        namespace: components["parameters"]["Namespace"];
        pipeline: components["parameters"]["Pipeline"];
        vertex: components["parameters"]["Vertex"];
      };
    };
    responses: {
      /** @description Pipeline vertex status */
      200: {
        headers: {
          ETag: components["headers"]["ETag"];
        };
        content: {
          "application/json": components["schemas"]["VertexStatus"];
        };
      };
      304: components["responses"]["NotModified"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["ValidationFailed"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** Get a compact MonoVertex summary */
  getMonoVertexSummary: {
    parameters: {
      header?: {
        "If-None-Match"?: components["parameters"]["IfNoneMatch"];
      };
      path: {
        namespace: components["parameters"]["Namespace"];
        monoVertex: components["parameters"]["MonoVertex"];
      };
    };
    responses: {
      /** @description MonoVertex summary */
      200: {
        headers: {
          ETag: components["headers"]["ETag"];
        };
        content: {
          "application/json": components["schemas"]["VertexSummary"];
        };
      };
      304: components["responses"]["NotModified"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["ValidationFailed"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** Get MonoVertex controller status */
  getMonoVertexStatus: {
    parameters: {
      header?: {
        "If-None-Match"?: components["parameters"]["IfNoneMatch"];
      };
      path: {
        namespace: components["parameters"]["Namespace"];
        monoVertex: components["parameters"]["MonoVertex"];
      };
    };
    responses: {
      /** @description MonoVertex status */
      200: {
        headers: {
          ETag: components["headers"]["ETag"];
        };
        content: {
          "application/json": components["schemas"]["VertexStatus"];
        };
      };
      304: components["responses"]["NotModified"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["ValidationFailed"];
      500: components["responses"]["InternalServerError"];
    };
  };
}
